/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package springOkta;

import com.sss.App;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
    }
}
